# Generated by Django 3.1 on 2021-10-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('discount', models.BooleanField(default=False, help_text='It applies a 30% discount.', verbose_name='discount')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('value', models.DecimalField(decimal_places=2, help_text="Product value when sale it's created.", max_digits=11, verbose_name='value')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount.', max_digits=11, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'sale line',
                'verbose_name_plural': 'sale lines',
                'db_table': 'sale_lines',
            },
        ),
    ]
