# Generated by Django 3.1 on 2021-10-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.BooleanField(default=1, help_text='It applies a 30% discount.', verbose_name='discount'),
            preserve_default=False,
        ),
    ]
