# Generated by Django 3.1 on 2021-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total amount.', max_digits=11, verbose_name='value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleline',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Product value when sale it's created.", max_digits=11, verbose_name='value'),
            preserve_default=False,
        ),
    ]
