# Generated by Django 3.1 on 2021-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20211015_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.BooleanField(default=False, help_text='It applies a 30% discount.', verbose_name='discount'),
        ),
    ]
