version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./compose/production/Dockerfile
        volumes:
            - .:/app
            - static_files:/static/
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings.production
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: postgres:10
        env_file:
            - ./.env
        environment:
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/
            - ./init-database.sh:/compose/postgre/init.sh
        volumes:
            - pgdata:/var/lib/postgresql/data/
    nginx:
        build:
            context: .
            dockerfile: ./compose/nginx/Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - app:app
        volumes:
            - ./keys/:/certificates/
            - static_files:/static/
        depends_on:
            - app

volumes:
    pgdata:
    static_files:
